# Generated by Django 5.2.2 on 2025-06-25 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmokingQuitData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quit_date", models.DateField(default=django.utils.timezone.now)),
                ("cost_per_day", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
