# Generated by Django 5.2.2 on 2025-06-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SmokingQuitData",
        ),
    ]
